// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekhowlufagfblwvsldlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVraG93bHVmYWdmYmx3dnNsZGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjQ4ODMsImV4cCI6MjA3MjY0MDg4M30.wfAzrCLM0nd9KTPNU1unmmauySL8rvMA76O0iG95oRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});